#!/usr/bin/env python

import argparse
import csv
import sys


parser = argparse.ArgumentParser()
parser.add_argument("--in-file", default="-", help="input file")
parser.add_argument("--in-delimiter", default=",", help="input delimiter")
parser.add_argument("--in-quote", default='"', help="input quote")
parser.add_argument("--out-file", default="-", help="output file")
parser.add_argument("--out-delimiter", default=",", help="output delimiter")
parser.add_argument("--out-quote", default='"', help="output quote")

args = parser.parse_args()


def process_delimiter(delimiter):
    if delimiter.lower() == "tab" or delimiter == "\\t":
        delimiter = "\t"
    return delimiter


in_delimiter = process_delimiter(args.in_delimiter)
out_delimiter = process_delimiter(args.out_delimiter)


if args.in_file == "-":
    in_fp = sys.stdin
else:
    in_fp = open(args.in_file, "r")


if args.out_file == "-":
    out_fp = sys.stdout
else:
    out_fp = open(args.out_file, "w")


in_reader = csv.reader(in_fp, delimiter=in_delimiter, quotechar=args.in_quote)

out_writer = csv.writer(out_fp, delimiter=out_delimiter, quotechar=args.out_quote)

for row in in_reader:
    out_writer.writerow(row)
